name: 🐛 Bug Report
description: Report a bug to help us improve the Strapi Prometheus plugin
title: '[BUG] '
labels: ['bug']
assignees:
  - XanderD99
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us understand and fix the issue.

  - type: textarea
    id: bug-description
    attributes:
      label: 🐛 Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 🔄 Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Step one
        2. Step two  
        3. Step three
        4. Step four
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: ✅ Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: ❌ Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened instead?
    validations:
      required: true

  - type: input
    id: strapi-version
    attributes:
      label: Strapi Version
      description: What version of Strapi are you using?
      placeholder: "e.g. 5.0.0"
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of the Strapi Prometheus plugin are you using?
      placeholder: "e.g. 2.2.2"
    validations:
      required: true

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      description: How did you install the plugin?
      options:
        - npm
        - yarn
        - pnpm
        - other
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: What operating system are you using?
      placeholder: "e.g. macOS 13.0, Ubuntu 22.04, Windows 11"
    validations:
      required: true

  - type: input
    id: nodejs-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: "e.g. 18.17.0"
    validations:
      required: true

  - type: input
    id: package-manager
    attributes:
      label: Package Manager
      description: What package manager and version are you using?
      placeholder: "e.g. npm 9.0.0, yarn 3.6.0"
    validations:
      required: true

  - type: input
    id: prometheus-version
    attributes:
      label: Prometheus Version
      description: What version of Prometheus are you using?
      placeholder: "e.g. 2.45.0"

  - type: dropdown
    id: metrics-server
    attributes:
      label: Metrics Server Setup
      description: How is your metrics server configured?
      options:
        - Dedicated server on separate port
        - Main Strapi server
        - Other
    validations:
      required: true

  - type: dropdown
    id: default-metrics
    attributes:
      label: Default Metrics Enabled
      description: Are default metrics enabled in your configuration?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: 📊 Configuration
      description: Share your plugin configuration (remove sensitive data)
      placeholder: |
        // config/plugins.js or config/plugins.ts
        prometheus: {
          enabled: true,
          config: {
            // Your configuration here
          }
        }
      render: javascript

  - type: textarea
    id: logs-errors
    attributes:
      label: 📋 Logs/Error Messages
      description: If applicable, add error messages or relevant log outputs
      placeholder: Paste error messages or logs here
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here or paste image URLs

  - type: textarea
    id: additional-context
    attributes:
      label: 🔍 Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Are you using any other Strapi plugins that might conflict?
        - Have you tried with a fresh Strapi installation?
        - Any custom middleware or modifications?

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      description: Please check the boxes that apply
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided all the requested information above
          required: true
        - label: I have tested this with the latest version of the plugin
          required: true
        - label: I have checked the troubleshooting guide in the README
          required: false